// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SharedDir } from "./SharedDir";

export type BrowseResult = { username: string, dirs: Array<SharedDir>, 
/**
 * Folders only buddies of that user can download from.
 */
lockedDirs: Array<SharedDir>, error: string | null, };
