// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Presence } from "./Presence";

export type Buddy = { username: string, presence: Presence, note: string, lastSeenMs: number | null, files: number | null, };
