// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileInfo } from "./FileInfo";
import type { Source } from "./Source";

/**
 * One folder at one peer.
 */
export type Candidate = { 
/**
 * Stable within a search: `username` + folder.
 */
id: string, source: Source, 
/**
 * Remote folder path (without trailing separator).
 */
folder: string, files: Array<FileInfo>, totalSize: number, };
