// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatMessage = { 
/**
 * Room name, or the other user for private messages.
 */
channel: string, username: string, text: string, atMs: number, own: boolean, 
/**
 * "/me" style action.
 */
action: boolean, };
