// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Codec = "flac" | "alac" | "wav" | "aiff" | "mp3" | "aac" | "ogg" | "opus" | "other";
