// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";
import type { Presence } from "./Presence";

export type Conversation = { username: string, last: ChatMessage | null, unread: number, presence: Presence, };
