// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Codec } from "./Codec";

/**
 * Payload of `download.verified` / `download.completed`.
 */
export type DownloadedFile = { jobId: string, localPath: string, title: string, artist: string | null, album: string | null, trackNumber: number | null, durationSecs: number | null, codec: Codec, sampleRate: number | null, bitDepth: number | null, bitrateKbps: number | null, size: number, };
