// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionManifest } from "./ExtensionManifest";

export type ExtensionInfo = { manifest: ExtensionManifest, enabled: boolean, 
/**
 * Absolute folder the extension was loaded from.
 */
dir: string, error: string | null, builtin: boolean, };
