// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Delivered to extension workers that hold `events:<name>`.
 */
export type ExtensionEvent = { 
/**
 * "download.verified", "download.completed", "search.completed", "pm.received".
 */
name: string, payload: JsonValue, };
