// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExtensionManifest = { id: string, name: string, version: string, description: string, author: string | null, 
/**
 * Worker script, relative to the extension folder.
 */
main: string, 
/**
 * Optional settings/panel page, rendered in a sandboxed iframe.
 */
panel: string | null, 
/**
 * e.g. "events:download.verified", "fs:write:~/Music/rekordbox", "notify".
 */
permissions: Array<string>, };
