// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Codec } from "./Codec";

/**
 * One file as a peer advertises it. `path` is the full remote path with
 * Soulseek's `\` separators, exactly as needed to request the file.
 */
export type FileInfo = { path: string, size: number, codec: Codec, bitrateKbps: number | null, vbr: boolean | null, sampleRate: number | null, bitDepth: number | null, durationSecs: number | null, };
