// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ItemState = { "kind": "pending" } | { "kind": "queued", position: number | null, } | { "kind": "downloading" } | { "kind": "verifying" } | { "kind": "verified" } | { "kind": "rejected" } | { "kind": "keptAnyway" } | { "kind": "failed", reason: string, };
