// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemState } from "./ItemState";
import type { Verdict } from "./Verdict";

export type ItemView = { 
/**
 * File name without the folder, the key the UI and events use.
 */
name: string, size: number, bytes: number, state: ItemState, localPath: string | null, verdict: Verdict | null, };
