// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JobStatus = { "kind": "waiting" } | { "kind": "queued", position: number | null, } | { "kind": "downloading" } | { "kind": "recovering", reason: string, } | { "kind": "verifying" } | { "kind": "done" } | { "kind": "failed", reason: string, } | { "kind": "paused" } | { "kind": "cancelled" };
