// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemView } from "./ItemView";
import type { JobStatus } from "./JobStatus";
import type { LogEntry } from "./LogEntry";

export type JobView = { id: string, title: string, artist: string | null, formatLabel: string, status: JobStatus, 
/**
 * A short line under the status ("from deepcrates", "failed the lossless check").
 */
detail: string, currentUser: string | null, 
/**
 * 1-based position of the current source, and how many there are.
 */
sourceIndex: number, sourceCount: number, items: Array<ItemView>, bytes: number, total: number, speed: number, 
/**
 * Seconds until the stuck rule switches source, while waiting in a queue.
 */
switchInSecs: number | null, log: Array<LogEntry>, outputDir: string, createdMs: number, finishedMs: number | null, };
