// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One remote file to check against the local library (`owned_check`).
 */
export type OwnedQuery = { path: string, size: number, };
