// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StuckRules } from "./StuckRules";
import type { Tier } from "./Tier";
import type { VerifySettings } from "./VerifySettings";

export type QualityProfile = { id: string, name: string, 
/**
 * The profile Needle ships with; it cannot be deleted.
 */
builtin: boolean, 
/**
 * Best first.
 */
tiers: Array<Tier>, 
/**
 * Skip peers whose queue is longer than this (when known).
 */
maxQueue: number, preferComplete: boolean, verify: VerifySettings, stuck: StuckRules, };
