// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileInfo } from "./FileInfo";
import type { Source } from "./Source";

/**
 * One peer's raw answer to a search: what the backend feeds the engine.
 */
export type RawResult = { source: Source, files: Array<FileInfo>, };
