// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Candidate } from "./Candidate";

/**
 * A folder that looks like one release, with every peer that holds an
 * identical copy (same file names and sizes) as fallbacks.
 */
export type Release = { id: string, title: string, artist: string | null, year: number | null, best: Candidate, 
/**
 * Identical copies at other peers, best first.
 */
alternates: Array<Candidate>, 
/**
 * Index into the profile's tiers this release satisfies.
 */
tier: number, 
/**
 * e.g. "FLAC 16/44.1", "MP3 320", "FLAC 24/96".
 */
formatLabel: string, 
/**
 * Audio files in `best`.
 */
trackCount: number, 
/**
 * Most audio files seen for this release across all peers; more than
 * `track_count` means this copy is incomplete.
 */
expectedTracks: number, score: number, 
/**
 * Why the release is hidden, in plain English; `None` when it is shown.
 */
hiddenReason: string | null, };
