// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";
import type { RoomMember } from "./RoomMember";

export type RoomEventPayload = { "kind": "message", message: ChatMessage, } | { "kind": "joined", room: string, member: RoomMember, } | { "kind": "left", room: string, username: string, } | { "kind": "ticker", room: string, username: string, text: string, } | { "kind": "listChanged" };
