// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";
import type { RoomMember } from "./RoomMember";

export type RoomView = { name: string, members: Array<RoomMember>, messages: Array<ChatMessage>, 
/**
 * Ticker lines set by members: (username, text).
 */
tickers: Array<[string, string]>, private: boolean, owner: string | null, };
