// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Presence } from "./Presence";

export type RoomMember = { username: string, presence: Presence, files: number | null, avgSpeed: number | null, operator: boolean, };
