// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoomSummary = { name: string, users: number, private: boolean, joined: boolean, };
