// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HiddenCounts } from "./HiddenCounts";
import type { Release } from "./Release";

export type SearchView = { searchId: string, query: string, releases: Array<Release>, 
/**
 * Folders that failed the profile, only filled when the caller asks for them.
 */
hiddenReleases: Array<Release>, hidden: HiddenCounts, totalFiles: number, totalPeers: number, done: boolean, };
