// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionState } from "./SessionState";

export type SessionStatus = { state: SessionState, username: string | null, error: string | null, listenPort: number, 
/**
 * Whether peers can reach us directly (UPnP/NAT-PMP mapped or tested open).
 */
portOpen: boolean | null, away: boolean, 
/**
 * Whether credentials are stored, so the app can log in on start.
 */
remembered: boolean, };
