// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Settings = { downloadDir: string, 
/**
 * Where files go while downloading; defaults inside `download_dir`.
 */
incompleteDir: string, rejectedDir: string, listenPort: number, portMapping: boolean, uploadSlots: number, 
/**
 * 0 = unlimited.
 */
uploadLimitKbps: number, downloadLimitKbps: number, buddiesFirst: boolean, activeProfileId: string, 
/**
 * Search terms appended as exclusions to every search (e.g. "-live").
 */
searchExclusions: Array<string>, autoJoinRooms: Array<string>, notifyPrivateMessages: boolean, notifyWishlistHits: boolean, };
