// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanStatus } from "./ScanStatus";
import type { Visibility } from "./Visibility";

export type ShareFolder = { path: string, visibility: Visibility, files: number, bytes: number, status: ScanStatus, };
