// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShareFolder } from "./ShareFolder";

export type SharesView = { folders: Array<ShareFolder>, sharedFiles: number, sharedFolders: number, 
/**
 * Files in the local library used for "you have this" in search.
 */
ownedFiles: number, 
/**
 * Files the scanner could not read.
 */
unreadable: Array<string>, };
