// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A peer that answered a search, decoupled from soulseek-rs-lib's types.
 */
export type Source = { username: string, freeSlot: boolean, 
/**
 * Average upload speed in bytes per second, as reported by the peer.
 */
avgSpeed: number, 
/**
 * Unknown when the library does not report it.
 */
queueLen: number | null, };
