// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StuckRules = { 
/**
 * Switch source after this long without receiving data.
 */
noDataSecs: number, 
/**
 * Switch source after waiting in a remote queue this long.
 */
queueWaitSecs: number, 
/**
 * Sources to try before searching again.
 */
maxSources: number, wishlistWhenExhausted: boolean, };
