// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Codec } from "./Codec";

export type Tier = { label: string, 
/**
 * "FLAC 16-bit", "MP3 320 kbps": the codecs this tier accepts.
 */
codecs: Array<Codec>, minBitDepth: number | null, minSampleRate: number | null, minBitrateKbps: number | null, 
/**
 * Accept VBR files whose average meets `min_bitrate_kbps` (V0).
 */
allowVbr: boolean, };
