// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the backend reports about one requested file.
 */
export type TransferStatus = { "kind": "queued", position: number | null, } | { "kind": "progress", bytes: number, total: number, speed: number, } | { "kind": "completed", localPath: string, } | { "kind": "failed", reason: string, } | { "kind": "timedOut" } | { "kind": "cancelled" };
