// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UploadView } from "./UploadView";

export type UploadsView = { uploads: Array<UploadView>, slots: number, slotsUsed: number, waiting: number, };
