// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UploadState = { "kind": "queued", position: number, } | { "kind": "uploading" } | { "kind": "done" } | { "kind": "failed", reason: string, } | { "kind": "cancelled" };
