// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UploadState } from "./UploadState";

export type UploadView = { username: string, 
/**
 * Path relative to the share root, for display.
 */
path: string, size: number, bytes: number, speed: number, state: UploadState, buddy: boolean, };
