// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Presence } from "./Presence";

export type UserProfile = { username: string, presence: Presence, avgSpeed: number | null, files: number | null, folders: number | null, freeSlot: boolean | null, queueLen: number | null, description: string | null, 
/**
 * data: URL of the user's picture, if they set one.
 */
picture: string | null, likes: Array<string>, dislikes: Array<string>, buddy: boolean, banned: boolean, ignored: boolean, };
