// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Codec } from "./Codec";

export type Verdict = { ok: boolean, codec: Codec, sampleRate: number | null, bitDepth: number | null, bitrateKbps: number | null, 
/**
 * Where the spectrum falls off a cliff, if it does.
 */
cutoffHz: number | null, nyquistHz: number, 
/**
 * Plain-language reason when `ok` is false ("stops at 16 kHz, typical of
 * a 128-192 kbps MP3 saved as FLAC").
 */
reason: string | null, 
/**
 * Average power per band from 0 Hz to Nyquist, in dB, 64 bands. For the UI.
 */
spectrum: Array<number>, };
