// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OnFail } from "./OnFail";
import type { Strictness } from "./Strictness";

export type VerifySettings = { enabled: boolean, strictness: Strictness, onFail: OnFail, };
