// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WishItem = { query: string, addedMs: number, lastRunMs: number | null, 
/**
 * Releases that matched the active profile on the last run.
 */
matches: number, 
/**
 * Search id holding the last run's results, to open them.
 */
searchId: string | null, };
